[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8 --protocol swd"
rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[alias]
fw-observation = "build -p swp-stm32f103-observation --release"
fw-control-footprint = "build -p swp-control-footprint-stm32f103 --release"
fw-live-shadow = "build -p swp-live-shadow-stm32f103 --release"
run-live-shadow = "run -p swp-live-shadow-stm32f103 --release"
fw-control-shadow = "build -p swp-control-shadow-stm32f103 --release"
run-control-shadow = "run -p swp-control-shadow-stm32f103 --release"
