[package]
name = "swp-stm32f103"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false
build = "build.rs"

[dependencies]
cortex-m.workspace = true
heapless.workspace = true
panic-halt.workspace = true
rtic.workspace = true
stm32f1xx-hal.workspace = true
swp-board-one-v2 = { path = "../../crates/board-one-v2" }
swp-mpu6050 = { path = "../../crates/mpu6050" }
swp-robot-domain = { path = "../../crates/robot-domain" }
swp-software-i2c = { path = "../../crates/software-i2c" }
swp-telemetry-protocol = { path = "../../crates/telemetry-protocol" }
